let services = {
  shampoo: 20,
  hairCut: 30,
  nailsCut: 15,
  hairColor: 60,
  deShedding: 80,
  deMatting: 100,
  bath: 40,
  fleaTreatment: 20,
  earCleaning: 15,
  teethCleaning: 30,
  analGlands: 20,
  nailGrinding: 15,
  nailPolish: 5,
  pawMassage: 10,
  bellyRubs: 5,
  cuddles: 5,
  kisses: 5,
  hugs: 5,
  snuggles: 5,
};
